### ISSUE TITLE
Question: Updated for 2.2?

### ISSUE THREAD

**Issue by matthewlenz** [radding/django-event-system#1]
I was searching /r/django for 'laravel events' and your post was the only hit.  I'm thinking about rewriting a legacy application and trying to decide between django and laravel (ugh, php).  But laravel's event/job/queue system is really kinda awesome.  Are you still using this project?  Planning on updating it to work with the newest Django?

**Comment by radding** [comment]
Hello! Sorry I missed this!

Yes, I will work to get this updated for 2.2

**Comment by radding** [comment]
solved with #2

**Comment by radding** [comment]
Here is the release that solves this: https://github.com/radding/django-event-system/releases/tag/v1.0.1
